### ISSUE TITLE
Error starting the bot

### ISSUE THREAD

**Issue by 1NUP** [Favna/Discord-Self-Bot#10]
Every time I run "yarn start" everything goes well until it reaches the token thing:

Authenticated using your token
Provider set to SQLiteProvider - will initialise once ready.
Using gateway wss://gateway.discord.gg/
[ws] [connection] Connecting to wss://gateway.discord.gg/
[ws] [connection] Connected to gateway wss://gateway.discord.gg/?v=6&compress=zlib-stream&encoding=json
[ws] [connection] Identifying as a new session
[ws] [connection] Setting a heartbeat interval for 41250ms
[ws] [connection] Server closed the WebSocket connection: 4004
[ws] [connection] Clearing heartbeat interval
Disconnected!
[ws] [connection] Tried to identify with an invalid token
[ws] [connection] Clearing heartbeat interval
[ws] [connection] Attempted to destroy WebSocket but no connection exists!
(node:13728) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error [TOKEN_INVALID]: An invalid token was provided.
(node:13728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13728) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'finalize' of null
Done in 2.93s.

**Comment by Favna** [comment]
This error means the token you put in the `auth.json` file is wrong. Please refer to the [wiki to see how to obtain your token](https://github.com/Favna/Discord-Self-Bot/wiki/Installation-&-Setup#grabbing-your-discord-account-token). I can't really help you there as I, like anyone else, should never get my eyes on your token.
