### ISSUE TITLE
Delete command

### ISSUE THREAD

**Issue by TimV2001** [Favna/Discord-Self-Bot#12]
Can you send me the code or file how I add the delete command. I am about to switch from Selfbot (I want to use this one) but i really want to have a delete command otherwise I stay on this one

**Comment by ev1l0rd** [comment]
Referencing #11 explains why it won't will not be done (memory concerns are the primary one and the secondary one is MANAGE_MESSAGES permissions).

Having said that, a command that loops over say the last 100 messages in the channel and removes any that are yours shouldn't be impossible. Just for looping over them and matching any that have their author set to msg.author (or client.author but they're identical on a selfbot) and then deleting them isn't impossible.

**Comment by TimV2001** [comment]
It is, because on other selfbots i can

**Comment by Favna** [comment]
Other selfbots are not my selfbot. Like I said, I'm not implementing this. If you don't like that then don't use my bot.
