### ISSUE TITLE
MessageEmbed is not defined 

### ISSUE THREAD

**Issue by GangGamerAK** [Favna/Discord-Self-Bot#13]
C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\src\commands\fun\copypasta.js:52
                            const cpEmbed = new MessageEmbed();
                                                ^

ReferenceError: MessageEmbed is not defined
    at fs.readFile (C:\Users\GangGamerAK\Desktop\Discord-Self-Bot\src\commands\fun\copypasta.js:52:49)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:503:3)

I got this error while running a copypasta file I added , and when I ran  it It crashed with error given above the bot is working great otherwise

**Comment by Favna** [comment]
Fixed in 0bef11c063880eb6a8488f5c30acfb5b1088caae. That was a mistake on my part.
