### ISSUE TITLE
[Invalid - Newer NodeJS version that described in Wiki] Can't start or install SelfBot

### ISSUE THREAD

**Issue by SamHep0803** [Favna/Discord-Self-Bot#16]
**Please describe the problem you are having in as much detail as possible:**
When I go to run the bot (`yarn start`) or install (`yarn install`) the dependencies I get an error saying that the engine 'node' is incompatible.

```
mylaptopname:Discord-Self-Bot-master mylaptopaccount$ yarn start
yarn run v1.3.2
$ yarn install
[1/5] 🔍  Validating package.json...
error discord-self-bot@6.0.0: The engine "node" is incompatible with this module. Expected version ">=8.0.0 <9.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
**Include a reproducible code sample here, if possible:**
```js

```

**Further details:**

- [X] I use yarn: 1.3.2
- [X] I use npm: 5.5.1
- node.js version: v9.2.0
- Operating system: Mac OS
- Priority this issue should have – please be realistic and elaborate if possible:

- [x] I have read the wiki

- [X] I am on the latest commit of the bot

**Comment by Favna** [comment]
The bot supports Node 8.0 till 8.9.X. Please download Node LTS (currently 8.9.1): 

https://nodejs.org/en/download/

**Comment by SamHep0803** [comment]
Oh, I thought it meant it can use 9.0 or higher. My programming instincts didn't kick in till just then.

**Comment by Favna** [comment]
For clarification, the way it is meant to be ready is "greater than or equal to 8.0 but smaller than 9.0"

**Comment by SamHep0803** [comment]
Yeah

**Comment by SamHep0803** [comment]
@Favna Do you have discord?
