### ISSUE TITLE
Rich Presence - Activity Command 

### ISSUE THREAD

**Issue by NootNootEh** [Favna/Discord-Self-Bot#18]
**Please describe the problem you are having in as much detail as possible:**
I've done the guide on how to setup Rich Presence with "Data.json" and it didn't work and didn't show anything, I've asked over 5 of my friends but it just shows my original information, reference photo here of what it looks like: https://streamvault.pw/src/z7a7N4.png | Here is a photo of the "Data.json" file https://streamvault.pw/src/y1c1r8.png | I retracted the image field/application so no one uses them. | Here is a picture of the console too. https://streamvault.pw/src/c4d3L9.png

So because the "Data.json" method didn't work, I decided to go through the route of using the "Activity" command that's for Rich Presence and right after I finish with the "Put URL if (Streaming)" it errors out with this error "TypeError [INVALID_TYPE]: Supplied name is not a string." which I don't understand what supplied name it's complaining about so I've went about changing the names of everything every time I tried. Here is a small little webm video containing what I put for $activity https://streamvault.pw/src/O8e3w5.webm

**Include a reproducible code sample here, if possible:**
```js

```

**Further details:**

- [X] I use yarn
- [ ] I use npm
- node.js version: Latest
- Operating system: Windows 7 Ultimate 
- Priority this issue should have – please be realistic and elaborate if possible: Medium

- [x] I have read the wiki

- [X] I am on the latest commit of the bot

**Comment by Favna** [comment]
Looks like you forgot to link the video. It would help.

**Comment by NootNootEh** [comment]
Oops sorry, Put the video for you.
