### ISSUE TITLE
Correctly installed yet it doesn't act like a bot?

### ISSUE THREAD

**Issue by konradmm** [Favna/Discord-Self-Bot#25]
**Please describe the problem you are having in as much detail as possible:**

**Further details:**

- [x] I use yarn
- [ ] I use npm
- node.js version: 8.9.4
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible:
Not sure tho if its a bug or im just an idiot

So basically, i installed everything correctly without any issues, when launching bot with yarn start everything goes smooth up to looped "sending heartbeat" so i assume everything is working 100% correctly.
However whenever i try writing to my bot using another account, he is just not responding, like it was no bot at all, just logged in. Tried writing on servers we both are, on private, tried mentioning him with 'prefix', used commands, nothing. No reply at all. Not sure if im missing something or?
Regards.

- [x] I have read the wiki

- [x] I am on the latest commit of the bot

**Comment by Favna** [comment]
The whole point of a selfbot is that you and only you can use your own commands. Anything else is the violating the rules of selfbots. Only the account from which you have used the token can use the bot. 

If you want a bot that can be used by multiple people I recommend you check out my public server bot Ribbon which has many of the same features as the selfbot:

[Add Ribbon to server](https://discord.now.sh/376520643862331396?p8)

[Ribbon GitHub](https://github.com/Favna/Ribbon)

[List of Ribbon commands](https://github.com/Favna/Ribbon/wiki/All-Commands)

**Comment by konradmm** [comment]
Oh i see, that was the main issue. I didnt exactly know how it should work ;p
Btw, I know its not a forums, however let me try. Is this any possible (and not violating any rules) to "autocheck" what other ppl sends to a channel and for example save it to text document file? Aka Chat Log that actually saves the messages as they were sent (before editing) ? Or that would be violating rules?

**Comment by konradmm** [comment]
And more likely about a bot itself. Is it possible for you to add the "feature" that will do as example:

I send command $coin
(+) Bot removes message with command
Bot is responding to the command.

So the command itself will be removed?

**Comment by Favna** [comment]
> So the command itself will be removed?

see [deletecommandmessages](https://github.com/Favna/Discord-Self-Bot/wiki/All-Commands#deletecommandmessages)

> to "autocheck" what other ppl sends to a channel and for example save it to text document file

A feature that another user has requested but I have not yet had time to implement is essentially linking 2 channels in that the selfbot would forward messages from channel A to Channel B. For example if Jphn Appleseed sends `Wow this is a cool message` to channel A the selfbot would detect that and send it as embed to Channel B which would then look something like this:

![](https://favna.s-ul.eu/AyuZCtqQ.png)
